
apiVersion: v1
kind: Service
metadata:
  name: employee-directory-service
spec:
  selector:
    app: employee-directory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
